update sync workflow

diff --git a/.github/workflows/odh-notebooks-sync.yml b/.github/workflows/odh-notebooks-sync.yml
--- a/.github/workflows/odh-notebooks-sync.yml
+++ b/.github/workflows/odh-notebooks-sync.yml
@@ -28,7 +28,7 @@ env:
 
 jobs:
   build:
-    runs-on: ubuntu-20.04-4core
+    runs-on: ubuntu-latest
     steps:
       - name: Clone repository and Sync
         run: |
@@ -44,7 +44,6 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: |
-            3.8
             3.9
 
       - name: Install pipenv and pip-versions
@@ -92,7 +91,23 @@ jobs:
             for dir in "${directories[@]}"; do
               counter=$((counter+1))
               echo "--Processing directory $counter '$dir' of total $total"
-              cd "$dir" && pipenv install ${package_name}~="${CODEFLARE_RELEASE_VERSION}" && pipenv --rm && cd -
+              cd "$dir"
+              #install specified package
+              if ! pipenv install ${package_name}~="${CODEFLARE_RELEASE_VERSION}"; then
+                echo "Failed to install ${package_name} with version ${CODEFLARE_RELEASE_VERSION} in $dir"
+                exit 1
+              fi
+              # Lock dependencies, ensuring pre-release are included and clear previous state
+              if ! pipenv lock --pre --clear ; then
+                echo "Failed to lock dependencies"
+                exit 1
+              fi
+              # remove virtual env and clear cache
+              if ! penv --rm --clear ; then
+                echo "Failed to remove virtual environment"
+                exit 1
+              fi
+              cd -
               echo "$((total-counter)) directories remaining.."
             done
           else
